services:
  rebecca:
    image:  rebeccapanel/rebecca:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/rebecca:/var/lib/rebecca

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /var/lib/rebecca/redis:/data
    ports:
      - "6379:6379"
